{% set name = "pylint-venv" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5f316da4474434241353866ac57cdfc6c3ade82020fcd0c0b3e25f87e724e3c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6

test:
  imports:
    - pylint_venv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jgosmann/pylint-venv/
  summary: pylint-venv provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mwawra
